version: '3'
services:
  api:
    build: .
    environment:
      - ENVIRONMENT=ci
    volumes:
      - .:/code
    deploy:
      resources:
        limits:
          memory: 400m
  celery:
    build: .
    volumes:
      - .:/code
    command: ["bash", "-c", "CELERY_WORKER_NAME=default ./start_celery_worker.sh -P prefork -Q default -c 1"]
  celery_indexing:
    build: .
    volumes:
        - .:/code
    command: ["bash", "-c", "CELERY_WORKER_NAME=indexing ./start_celery_worker.sh -P prefork -Q indexing -c 1"]
  celery_concurrent:
    build: .
    volumes:
      - .:/code
    command: ["bash", "-c", "CELERY_WORKER_NAME=concurrent ./start_celery_worker.sh -P prefork -Q concurrent -c 1"]
  celery_bulk_import_0_1:
    build: .
    volumes:
      - .:/code
  celery_bulk_import_0_2:
    build: .
    volumes:
      - .:/code
  celery_bulk_import_root:
    build: .
    volumes:
      - .:/code
  flower:
    build: .
    volumes:
      - .:/code
